### ISSUE TITLE
How can I make it work?

### ISSUE THREAD

**Issue by trozware** [necinc/elmmet#2]
Hi,

This looks really useful, however I cannot get it to work. I have it installed and I can see and select the "Emmet to Elm" option but nothing happens. Do I need to install some other plugins to make this work?

VSC 1.25.1

**Comment by maximalism2** [comment]
Hi @trozware, thanks for texting me!

I've checked it and it seems like the problem is caused by third-party module, which could be not available. Do you observe any error messages in your output console in VSCode?

**Comment by trozware** [comment]
Hi,

Thanks for the fast response.
I am not seeing anything in the Console or Debug Output.
I am new to VSC so let me know if there is anywhere else I should be looking or if you want me to check anything else.

Regards,
Sarah

Sarah Reichelt
sarah@troz.net (mailto:sarah@troz.net)
http://troz.net/
@trozware

**Comment by c50a326** [comment]
Also not working for me. I tried following exactly as demonstrated in the GIF's.

**Comment by maximalism2** [comment]
Hmmm..., okay

@c50a326 do you have a language mode set to `Elm` ?
![image](https://user-images.githubusercontent.com/8607893/43268334-055e28be-90f9-11e8-8485-7b3bc67bf749.png)
![image](https://user-images.githubusercontent.com/8607893/43268350-11802c32-90f9-11e8-9e40-f0f3a136e93c.png)

**Comment by ThomasWeiser** [comment]
Look really useful, thanks for making it!

But, same for me. No reaction when doing "Emmet to Elm"

**Comment by joelsyverud** [comment]
I had the same problem. No error in vscode proper, but if you pull up the developer tools you get this error message in the electron-js-console:

	[Extension Host] Error: Command failed: ./node_modules/.bin/elm-format --stdin 
	/bin/sh: ./node_modules/.bin/elm-format: No such file or directory
	at ChildProcess.exithandler (child_process.js:287:12)
	at emitTwo (events.js:126:13)
	at ChildProcess.emit (events.js:214:7)
	at maybeClose (internal/child_process.js:925:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

I got it working by changing `./node_modules/.bin/elm-format --stdin` to `elm-format --stdin` on line 49 in elmmet.js, since I have elm-format locally installed.

**Comment by maximalism2** [comment]
Oh, @joelsyverud thank you for your comment!! That's the culprit! I'll make the call to `elm-format` optional for some time and get rid of it at all when there will be some other replacement for `elm-format`

**Comment by maximalism2** [comment]
So guys, I've published new release with the fix for this issue
